### ISSUE TITLE
Grafana dashboard enhancement

### ISSUE THREAD

**Issue by yanksyoon** [canonical/wordpress-k8s-operator#45]
### Enhancement Proposal

Out of the listed (apache metrics)[https://github.com/canonical/wordpress-k8s-operator/pull/43#issuecomment-1427567340], it would be nice to have a Grafana dashboard that the SREs may need or rank the metrics in the order of importance.

**Comment by amandahla** [comment]
@yanksyoon is this issue still relevant?

**Comment by yanksyoon** [comment]
Created https://warthogs.atlassian.net/browse/ISD-2804 (ISD-2804) to keep track of this enhancement feature. @varshigupta12 @jdkandersson Please assign this to relevant person as discussed.
