### ISSUE TITLE
Remove outdated plugins

### ISSUE THREAD

**Issue by yanksyoon** [canonical/wordpress-k8s-operator#47]
### Bug Description

The following plugins are outdated/deprecated/removed due to violation of guidelines and are no longer available.

fruitful-shortcodes
hello
social-media-buttons-toolbar
wordpress-seo

### To Reproduce

https://wordpress.org/plugins/fruitful-shortcodes/ - removed due to violation of guidelines
https://wordpress.org/plugins/hello/ - not found
https://wordpress.org/plugins/social-media-buttons-toolbar/ - removed due to violation of guidelines
https://wordpress.org/plugins/wordpress-seo/ - unsupported version

### Environment

N/A

### Relevant log output

```shell
N/A
```

**Comment by cbartz** [comment]
@yanksyoon Can you please confirm if this is still an issue and create a jira ticket if so?

**Comment by yanksyoon** [comment]
Apart from wordpress-seo (used by webteam), all the other [plugins have been removed](https://github.com/canonical/wordpress-k8s-operator/blob/main/wordpress_rock/rockcraft.yaml#L99).
Closing, thanks!
