### ISSUE TITLE
Fix required status checks

### ISSUE THREAD

**Issue by jdkandersson** [canonical/wordpress-k8s-operator#56]
The required status checks are current skipped if a previous workflow fails. This means that GitHub doesn't treat them as required which can lead to accidentally merging the PR when the required status checks haven't passed. an `if: always()` should be added to the required status checks: https://github.com/canonical/wordpress-k8s-operator/blob/b7d1cd6becce16a71ccb97e62426dc1d7d2dfec9/.github/workflows/integration_test.yaml#L59

**Comment by cbartz** [comment]
Should be fixed, due to usage of operator-workflows.
