### ISSUE TITLE
Charm fails if it's relations are not ready yet

### ISSUE THREAD

**Issue by simskij** [canonical/wordpress-k8s-operator#67]
### Bug Description

If deployed together with mysql-k8s and related immediately, the charm goes into `install failed`, due to MySQL not yet being ready to accept the connection. We need to stand off until we're able to successfully connect from the charm before we try to go ahead with the installation.

### To Reproduce

1. juju deploy wordpress-k8s --channel edge && juju deploy mysql-k8s --channel edge && juju relate wordpress-k8s mysql-k8s:database && juju relate wordpress-k8s mysql-k8s:mysql
5. juju status --watch 1s

### Environment

juju 3.1+

### Relevant log output

```shell
unit-wordpress-0: 19:26:41 WARNING unit.wordpress/0.install Traceback (most recent call last):
unit-wordpress-0: 19:26:41 WARNING unit.wordpress/0.install   File "./src/charm.py", line 45, in <module>
unit-wordpress-0: 19:26:41 WARNING unit.wordpress/0.install     import types_
unit-wordpress-0: 19:26:41 WARNING unit.wordpress/0.install   File "/var/lib/juju/agents/unit-wordpress-0/charm/src/types_.py", line 37, in <module>
unit-wordpress-0: 19:26:41 WARNING unit.wordpress/0.install     class DatabaseConfig(NamedTuple):
unit-wordpress-0: 19:26:41 WARNING unit.wordpress/0.install   File "/var/lib/juju/agents/unit-wordpress-0/charm/src/types_.py", line 47, in DatabaseConfig
unit-wordpress-0: 19:26:41 WARNING unit.wordpress/0.install     hostname: str | None
unit-wordpress-0: 19:26:41 WARNING unit.wordpress/0.install TypeError: unsupported operand type(s) for |: 'type' and 'NoneType'
unit-wordpress-0: 19:26:41 ERROR juju.worker.uniter.operation hook "install" (via hook dispatching script: dispatch) failed: exit status 1
unit-wordpress-0: 19:26:41 INFO juju.worker.uniter awaiting error resolution for "install" hook
unit-wordpress-0: 19:26:42 INFO juju.worker.uniter awaiting error resolution for "install" hook
unit-wordpress-0: 19:26:42 INFO juju.worker.uniter awaiting error resolution for "install" hook
unit-wordpress-0: 19:26:46 INFO juju.worker.uniter awaiting error resolution for "install" hook
unit-mysql-0: 19:26:46 INFO unit.mysql/0.juju-log Configuring instance
unit-wordpress-0: 19:26:46 WARNING unit.wordpress/0.install Traceback (most recent call last):
unit-wordpress-0: 19:26:46 WARNING unit.wordpress/0.install   File "./src/charm.py", line 45, in <module>
unit-wordpress-0: 19:26:46 WARNING unit.wordpress/0.install     import types_
unit-wordpress-0: 19:26:46 WARNING unit.wordpress/0.install   File "/var/lib/juju/agents/unit-wordpress-0/charm/src/types_.py", line 37, in <module>
unit-wordpress-0: 19:26:46 WARNING unit.wordpress/0.install     class DatabaseConfig(NamedTuple):
unit-wordpress-0: 19:26:46 WARNING unit.wordpress/0.install   File "/var/lib/juju/agents/unit-wordpress-0/charm/src/types_.py", line 47, in DatabaseConfig
unit-wordpress-0: 19:26:46 WARNING unit.wordpress/0.install     hostname: str | None
unit-wordpress-0: 19:26:46 WARNING unit.wordpress/0.install TypeError: unsupported operand type(s) for |: 'type' and 'NoneType'
unit-wordpress-0: 19:26:47 ERROR juju.worker.uniter.operation hook "install" (via hook dispatching script: dispatch) failed: exit status 1
```

### Additional context

Deployed using the terraform provider, so everything is done as one operation. Reproduction steps are concatenated to represent that.

**Comment by weiiwang01** [comment]
Currently, WordPress will wait for database to be ready up to one minutes after database connection is provided in the database relation. After that, charm will go into blocked state, with MySQL error code (in your case `MySQL error 2003`) in the status message. Is this what happened?

**Comment by weiiwang01** [comment]
I see the problem, and I think it's not relevant to the database. The WordPress charm seems to be deployed on focal with Python 3.8. One of the recent change requires jammy / Python 3.10 to work.

**Comment by weiiwang01** [comment]
@simskij I will create a story to fix this problem or drop the support for focal. In the meantime, could you please deploy the WordPress charm with `--series` argument set to `jammy`? For example, `juju deploy wordpress-k8s --channel edge --series jammy`.

**Comment by simskij** [comment]
> I see the problem, and I think it's not relevant to the database. The WordPress charm seems to be deployed on focal with Python 3.8. One of the recent change requires jammy / Python 3.10 to work.

Right, it gets past the install stage if I supply jammy as the series. However, it still gets stuck in `blocked`/`idle` `MySQL error 2003`, which it never seems to recover from.

**Comment by jdkandersson** [comment]
@simskij Thanks for reporting this SImon, I was trying to understand, do you know why your deployment might have ended up using focal?

**Comment by simskij** [comment]
> @simskij Thanks for reporting this Simon, I was trying to understand, do you know why your deployment might have ended up using focal?

That was the default for the charm, afaict. Seems to be confirmed by https://github.com/canonical/wordpress-k8s-operator/issues/67
